apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
  namespace: teaching
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
    